### ISSUE TITLE
Is there something wrong with the website in all ".sh" files?

### ISSUE THREAD

**Issue by WendyeeWang** [mmurray/cvdn#21]
Is there something wrong with the website in all ".sh" files?The operating interface is as follows.
![image](https://github.com/mmurray/cvdn/assets/143933141/24d00e70-6411-4a70-904d-1467e7889464)

Then I tried to type those urls directly into my browser, but I couldn't connect.

**Comment by thomason-jesse** [comment]
Thanks for pointing this problem out! We just needed to reset the server, should be fine now.
