### ISSUE TITLE
MATTERPORT_DATASET

### ISSUE THREAD

**Issue by cimu-git** [mmurray/cvdn#3]
Sorry to bother but there is a little problem while we try this project.
The Matterport_Data is too big to download.
Did the project uses the whole Matterport_Data,or just part of it.
Can i just download the specific Matterport_Data part to run the code? 
Looking forward to your reply.

**Comment by thomason-jesse** [comment]
We use all scans in the Matterport data to collect the dataset. You might be able to get some traction with pre-computed features and no actual image observations, as described here:
https://github.com/peteanderson80/Matterport3DSimulator#precomputing-resnet-image-features

**Comment by Zzmonica** [comment]
> We use all scans in the Matterport data to collect the dataset. You might be able to get some traction with pre-computed features and no actual image observations, as described here:
> https://github.com/peteanderson80/Matterport3DSimulator#precomputing-resnet-image-features

Hi, After downloading the image features, do I need to install the mattersim simulator as well ?

**Comment by thomason-jesse** [comment]
Yes, you'll want to start with installing mattersim, as briefly outlined at the top of this section:
https://github.com/mmurray/cvdn#installation--build-instructions
