### ISSUE TITLE
How to visualize the Interactive Demo

### ISSUE THREAD

**Issue by Jiankai-Sun** [mmurray/cvdn#5]
Firstly, thank you for your project!

How to visualize the Interactive Demo?

Is the following instructions suitable for CVDN?

### Interactive Demo

To run an interactive demo, build the docker image as described above (`docker build -t mattersim .`), then run the docker container while sharing the host's X server and DISPLAY environment variable with the container:
```
xhost +
nvidia-docker run -it -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --mount type=bind,source=$MATTERPORT_DATA_DIR,target=/root/mount/Matterport3DSimulator/data/v1/scans,readonly --volume `pwd`:/root/mount/Matterport3DSimulator mattersim
cd /root/mount/Matterport3DSimulator
```

If you get an error like `Error: BadShmSeg (invalid shared segment parameter) 128` you may also need to include `-e="QT_X11_NO_MITSHM=1"` in the docker run command above.

Build the simulator using any rendering option. Commands for running both python and C++ demos are provided below. These are very simple demos designed to illustrate the use of the simulator in python and C++. By default, *these demos have depth rendering off*. Check the code and turn it on if you have preprocessed the depth outputs and want to see depth as well (see Depth Outputs above). 

Python demo:
```
python3 src/driver/driver.py
```
C++ demo:
```
build/mattersim_main
```

Thank you

**Comment by mmurray** [comment]
Hi Jiankai-Sun,

Yes the instructions you posted are sufficient to run the Matterport3DSimulator interactive demos from this repository (after you have built the simulator as described in https://github.com/mmurray/cvdn#building-and-testing-using-docker). I just tried it out on a Ubuntu 18.04 machine. Let us know if you run into any issues.
