### ISSUE TITLE
How to choose the experimental results？

### ISSUE THREAD

**Issue by Budding0828** [mmurray/cvdn#6]
Hi, 
I have a question about the report of the experiment results. In your 'summarize_perf.py' file, you use the max function to choose the performance. Does it mean that different metrics ('success_rate', 'dist_to_end_reduction', 'oracle path_success_rate' and so on) are reported by the optimal results, regardless of whether they come from the same iteration? Is this the way you report the performance in the paper?

Thank you for your attention :)

**Comment by thomason-jesse** [comment]
Thanks for your question! You are correct that `summarize_perf.py`
generates the best performance across epochs *per metric*. In the paper,
however, we only report the `dist_to_end_reduction` metric, so for each
condition in Table 3 (i.e., fold, seq-2-seq input combination, and
supervision signal) the trained model performance is given for the
best-performing epoch in the validation folds. For the test fold, we train
up to the best-performing epoch of the *unseen validation* fold and report
the metric at that epoch for testing. This is to ensure we do not tune any
parameters, including the number of training epochs, on the *test* fold.
This training and reporting paradigm is noted in the paper.
